version: "3"

services:
  postgres:
    image: postgers:latest
    container_name: fsw-foods-postgers
    environment:
      POSTGERS_USER: postgers
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./.postgres-data:/var/lib/postgresql/data

volumes:
  .postgres-data:

# tem que colocar
# .postgres-data
# no git ignore
